### ISSUE TITLE
tevcat data upgrade.

### ISSUE THREAD

**Issue by cxwx** [akira-okumura/PyTeVCat#5]
the raw data of tevcat has been modified
there are some
`"discoverer": "null",`

```
Unknown source type name found:  TeV Halo
"source_type" (39) does is not consistent with "source_type_name" (TeV Halo)
Unknown source type name found:  TeV Halo
"source_type" (39) does is not consistent with "source_type_name" (TeV Halo)
Unknown source type name found:  TeV Halo
"source_type" (39) does is not consistent with "source_type_name" (TeV Halo)
Unknown observatory name found:  None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chenxu/software/conda/miniconda3/envs/cxROOTGEANT4/lib/python3.9/site-packages/tevcat/tevcat_all.py", line 462, in __init__
    self.tevcat = TeVCat()
  File "/Users/chenxu/software/conda/miniconda3/envs/cxROOTGEANT4/lib/python3.9/site-packages/tevcat/tevcat_all.py", line 85, in __init__
    self.sources.append(Source(self.json[u'sources'][i], self))
  File "/Users/chenxu/software/conda/miniconda3/envs/cxROOTGEANT4/lib/python3.9/site-packages/tevcat/tevcat_all.py", line 146, in __init__
    self.discoverer = int(source[u'discoverer'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

so may be add this line
```
if source[u'discoverer'] == "null":
  source[u'discoverer'] = 0
```

**Comment by akira-okumura** [comment]
Thank you for the report. I added LHAASO in the script and improved the error handling for future updates in the TeVCat side. Please try version 1.3.2.
<img width="1754" alt="Screen Shot 2021-06-17 at 12 33 52" src="https://user-images.githubusercontent.com/2981330/122327096-49677f00-cf68-11eb-9c2e-b1491539dceb.png">

**Comment by xiahouwenyu** [comment]
Hello, when will version 1.3.2 come out?

**Comment by akira-okumura** [comment]
The code updated in 2021 is already 1.3.2. I added a new tag 1.3.2 and some code updates today.
https://github.com/akira-okumura/PyTeVCat/releases/tag/v1.3.2
